name: rename branch

on:
  workflow_dispatch:

jobs:

  get-repositories-to-rename-branch:
      runs-on: ubuntu-latest
      outputs:
        REPOSITORIES: ${{ steps.set-matrix.outputs.REPO }}
        OWNER: ${{ steps.set-owner.outputs.OW}}
        USER: ${{ steps.set-user.outputs.US}}
      steps:
        - name: Checkout to repository
          uses: actions/checkout@v3
       
        - name: Set matrix data
          id: set-matrix
          run: echo "REPO=$(jq -c -r '.repositories | map(.repo_name)' < ./repositories.json)" >> $GITHUB_OUTPUT 

        - name: Set owner
          id: set-owner
          run: echo "OW=$(jq -r '.owner' repositories.json)" >> $GITHUB_OUTPUT

        - name: Set user
          id: set-user
          run: echo "US=$(jq -r '.owner' repositories.json)" >> $GITHUB_OUTPUT 
 

  rename-branch:
    runs-on: ubuntu-latest
    needs: [get-repositories-to-rename-branch]
    strategy:
        max-parallel: 1
        # SET MATRIX WITH repositories TO MIGRATE
        matrix: 
            repositorie: ${{fromJson(needs.get-repositories-to-rename-branch.outputs.REPOSITORIES)}}

    steps:
      - uses: actions/checkout@v3

      - name: rename master
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          OWNER: ${{ needs.get-repositories-to-rename-branch.outputs.OWNER }}
          USER: ${{ needs.get-repositories-to-rename-branch.outputs.USER }}
        run: |


          git clone https://${{ env.USER }}:${{ env.GH_TOKEN }}@github.com/${{ env.OWNER }}/${{ matrix.repositorie }}.git
          cd ${{ matrix.repositorie }}
          # Obtener el nombre de la rama actual
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "la rama es $current_branch"
          # Verificar si la rama actual es "master"
          if [ "$current_branch" == "master" ]; then

            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.OWNER }}/${{ matrix.repositorie }}/branches/master/rename \
            -d '{"new_name":"main"}'

              echo "La rama master ha sido renombrada a main."
          else
              echo "La rama actual no es master, no se realizaron cambios."
          fi



