name: rename branch

on:
  workflow_dispatch:

jobs:

  get-repositories-to-rename-branch:
      runs-on: ubuntu-latest
      outputs:
        REPOSITORIES: ${{ steps.set-matrix.outputs.REPO }}
        OWNER: ${{ steps.set-owner.outputs.OW}}
        USER: ${{ steps.set-user.outputs.US}}
      steps:
        - name: Checkout to repository
          uses: actions/checkout@v3
       
        - name: Set matrix data
          id: set-matrix
          run: echo "REPO=$(jq -c -r '.repositories | map(.repo_name)' < ./repositories.json)" >> $GITHUB_OUTPUT 

        - name: Set owner
          id: set-owner
          run: echo "OW=$(jq -r '.owner' repositories.json)" >> $GITHUB_OUTPUT

        - name: Set user
          id: set-user
          run: echo "US=$(jq -r '.owner' repositories.json)" >> $GITHUB_OUTPUT 
 

  rename-branch:
    runs-on: ubuntu-latest
    needs: [get-repositories-to-rename-branch]
    strategy:
        max-parallel: 1
        # SET MATRIX WITH repositories TO MIGRATE
        matrix: 
            repositorie: ${{fromJson(needs.get-repositories-to-rename-branch.outputs.REPOSITORIES)}}

    steps:
      - uses: actions/checkout@v3

      - name: Add File to Another Repo
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          OWNER: ${{ needs.get-repositories-to-rename-branch.outputs.OWNER }}
          USER: ${{ needs.get-repositories-to-rename-branch.outputs.USER }}
        run: |


          git clone https://${{ env.USER }}:${{ env.GH_TOKEN }}@github.com/${{ env.OWNER }}/${{ matrix.repositories }}.git
          cd ${{ matrix.repositories }}
          # Obtener el nombre de la rama actual
          current_branch=$(git rev-parse --abbrev-ref HEAD)

          # Verificar si la rama actual es "master"
          if [ "$current_branch" == "master" ]; then
              # Renombrar la rama local
              git branch -m master main
              
              # Empujar los cambios al repositorio remoto
              git push -u origin main
              
              # Actualizar la rama predeterminada en el repositorio remoto (opcional)
              # Consulta la documentación del servicio específico para obtener instrucciones
              
              # Actualizar las configuraciones locales de rastreo (opcional)
              git branch -u origin/main
              
              echo "La rama master ha sido renombrada a main."
          else
              echo "La rama actual no es master, no se realizaron cambios."
          fi



